

# This file was *autogenerated* from the file edwards521.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = Integer(0x1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff); _sage_const_0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa4331 = Integer(0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa4331); _sage_const_1 = Integer(1); _sage_const_48 = Integer(48); _sage_const_14 = Integer(14); _sage_const_2 = Integer(2); _sage_const_864 = Integer(864); _sage_const_34 = Integer(34); _sage_const_5 = Integer(5); _sage_const_12 = Integer(12); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0)
from utils import (
    Edwards_Neutral_Element_Affine,
    Edwards_Neutral_Element_Projective,
    AffinePoint,
    ProjectivePoint
)
# constants from https://neuromancer.sk/std/other/E-521
p = _sage_const_0x1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 
K = GF(p)
# d is used to construct edwards curve.
d = K(
    _sage_const_0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa4331 )
# This is a weierstrass curve, that is birationally equivalent to the edwards curve with the d value above.
E = EllipticCurve(K, (
    K(-_sage_const_1  / _sage_const_48 ) * (_sage_const_1  + _sage_const_14  * d + d ** _sage_const_2 ),  # a
    K(_sage_const_1  / _sage_const_864 ) * (_sage_const_1  + d) * (-_sage_const_1  + _sage_const_34  * d - d ** _sage_const_2 )  # b
))

# conversions found https://neuromancer.sk/std/other/Ed25519
def to_weierstrass(P: AffinePoint) -> AffinePoint:
    x = (_sage_const_5  + P.y - _sage_const_5  * d * P.y - d) / (_sage_const_12  - _sage_const_12  * P.y)
    y = (_sage_const_1  + P.y - d * P.y - d) / (_sage_const_4  * P.x - _sage_const_4  * P.x * P.y)
    return AffinePoint(x, y)


def to_edwards(P: AffinePoint) -> AffinePoint:
    u, v = P
    y = (_sage_const_5  - _sage_const_12  * u - d) / (-_sage_const_12  * u - _sage_const_1  + _sage_const_5  * d)
    x = (_sage_const_1  + y - d * y - d) / (_sage_const_4  * v - _sage_const_4  * v * y)
    return AffinePoint(x, y)

def edwards_addition(P1: ProjectivePoint, P2: ProjectivePoint) -> ProjectivePoint:
    # page 21
    X1, Y1, Z1 = P1
    X2, Y2, Z2 = P2

    A = Z1 * Z2
    B = A * A
    C = X1 * X2
    D = Y1 * Y2
    E = d * C * D
    F = B - E
    G = B + E

    X3 = A * F * ((X1 + Y1) * (X2 + Y2) - C - D)
    Y3 = A * G * (D - C)
    Z3 = G * F

    return ProjectivePoint(X3, Y3, Z3)

def edwards_scalar_multiplication(P: ProjectivePoint, scalar: int) -> ProjectivePoint:
    Q = P
    R = Edwards_Neutral_Element_Projective
    while scalar > _sage_const_0 :
        if scalar % _sage_const_2  == _sage_const_1 :
            R = edwards_addition(R, Q)
        Q = edwards_addition(Q, Q)
        scalar = scalar // _sage_const_2 

    return R


def edwards_negation(P: ProjectivePoint) -> ProjectivePoint:
    X, Y, Z = P
    return ProjectivePoint(-X, Y, Z)


"""
def montgomery_ladder(P: ProjectivePoint, k: int):
    k_bin = bin(k)[2:] 
    k_bin = k_bin[::-1]  
    R0, R1 = P, edwards_doubling(P)

    for i in range(len(k_bin) - 2, -1, -1): 
        if k_bin[i] == "0":
            R0, R1 = edwards_doubling(R0), edwards_addition(R0, R1)
        else:
            R0, R1 = edwards_addition(R0, R1), edwards_doubling(R1)

    return R0
    """

